/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ColorsMenu: typeof import('./src/components/ColorsMenu.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Heads: typeof import('./src/components/Heads.vue')['default']
    ModularOperation: typeof import('./src/components/ModularOperation.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Payout: typeof import('./src/components/Payout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Snack: typeof import('./src/components/Snack.vue')['default']
    SubComments: typeof import('./src/components/SubComments.vue')['default']
  }
}
